### ISSUE TITLE
What about a release?

### ISSUE THREAD

**Issue by jensens** [collective/collective.recipe.supervisor#11]
some important changes are hanging - i can do it too, I just need pypi access

**Comment by jensens** [comment]
ping?

**Comment by jensens** [comment]
I can do the release if someone may give me permissions at pypi.

**Comment by mauritsvanrees** [comment]
@nueces @domenkozar I hope I have the correct github names. Can one of you grant PYPI rights at https://pypi.python.org/pypi/collective.recipe.supervisor to Jens Klein? That is pypi user id 'jensens'.

**Comment by domenkozar** [comment]
done
