### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.recipe.supervisor#19]
Could we have a new release please? There are just a few minor changes, but they have been on master since 1.5 years, so would be good to have a 0.21 release (or 1.0 since it is pretty stable).

**Comment by mauritsvanrees** [comment]
Once PR #22 is merged, I hope we can have a new release.

**Comment by gforcada** [comment]
Release done 😃

**Comment by mauritsvanrees** [comment]
Thanks!

**Comment by mauritsvanrees** [comment]
Ah, you merged the PR, but no release, as you have no rights. 
@jensens can you make a release?

**Comment by gforcada** [comment]
Sorry, I meant PR merged 😅

**Comment by jensens** [comment]
Released!
