### ISSUE TITLE
Does not work with Python 3

### ISSUE THREAD

**Issue by pcart-grandjean** [collective/collective.recipe.supervisor#21]
Hello,

I try to migrate all my applications to Python 3. And with buildout and the collective.recipe.supervisor I get an error with the most simplistic configuration file:
buildout.cfg: <<
buildout]
parts = supervisor

[supervisor]
recipe = collective.recipe.supervisor
>>

With Python 3.6.4, the command 'buildout' generates a ValueError.

If I switch to Python 2.7.12, there are no errors. In both cases I use zc.buildout-2.13.1.

Please see configuration file and console log for more details.

Thanks,
Pierre
[Console](https://github.com/collective/collective.recipe.supervisor/files/2915320/builout.txt)
[buildout.cfg](https://github.com/collective/collective.recipe.supervisor/files/2915326/buildout.cfg.txt)

**Comment by mauritsvanrees** [comment]
This is because the `supervisor` package does not have a Python3 compatible release yet. See the rather lengthy [issue in the supervisor issue tracker](https://github.com/Supervisor/supervisor/issues/1060). It is mostly lengthy because people keep asking for an alpha or beta release.

You could try out the master branch.  This buildout works for me:

```
[buildout]
extensions = mr.developer
parts = supervisor
auto-checkout = *

[sources]
supervisor = git https://github.com/Supervisor/supervisor.git

[supervisor]
recipe = collective.recipe.supervisor
```

**Comment by mnaberez** [comment]
[Supervisor 4.0.0](https://pypi.org/project/supervisor/) (PyPI package; supports Python 3.4+ and 2.7)

**Comment by mauritsvanrees** [comment]
Thanks for the heads-up. supervisor 4.0.1 is out a week later. Seems to work fine with your basic buildout config:

```
$ bin/python --version
Python 3.7.3
maurits@MauritsBook:sv $ cat buildout.cfg 
[buildout]
parts = supervisor

[supervisor]
recipe = collective.recipe.supervisor
$ bin/buildout 
Creating directory '/Users/maurits/tmp/sv/parts'.
Creating directory '/Users/maurits/tmp/sv/develop-eggs'.
Getting distribution for 'collective.recipe.supervisor'.
Got collective.recipe.supervisor 0.20.
Unused options for buildout: 'zope-directory'.
Installing supervisor.
Getting distribution for 'supervisor'.
Got supervisor 4.0.1.
Getting distribution for 'meld3>=1.0.0'.
zip_safe flag not set; analyzing archive contents...
Got meld3 1.0.2.
Generated script '/Users/maurits/tmp/sv/bin/supervisord'.
Generated script '/Users/maurits/tmp/sv/bin/supervisorctl'.
$ bin/supervisord
$ bin/supervisorctl status
$ bin/supervisorctl
supervisor> help

default commands (type help <topic>):
=====================================
add    exit      open  reload  restart   start   tail   
avail  fg        pid   remove  shutdown  status  update 
clear  maintail  quit  reread  signal    stop    version

supervisor> quit
```
